arch              = "arm64"
guest_os_type     = "Ubuntu_arm64"
chipset           = "armv8virtual"
nic_type          = "virtio"
iso_url           = "https://cdimage.ubuntu.com/releases/24.04.4/release/ubuntu-24.04.4-live-server-arm64.iso"
iso_checksum      = "file:https://cdimage.ubuntu.com/releases/24.04.4/release/SHA256SUMS"
storage_interface = "virtio"
